## Упражнения по библиотеке Numpy

In [1]:
import numpy as np
import random

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
random_array = np.random.randint(-1, 15, 10)
random_array[(3 < random_array) & (random_array < 8)] *= -1

**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
random_array = np.random.randint(-1, 15, 10)
random_array[random_array.argmax()] = 0
random_array

array([ 0, 12,  6,  6, 10,  3,  5, 10,  9,  6])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
array_1 = np.random.randint(1, 5, size=(2, 2))
array_2 = np.random.randint(1, 10, size=(2, 2))
for i in range(len(array_1)):
    for j in range(len(array_2[0])):
        print(array_1[i][j], array_2[i][j])

1 8
3 5
3 8
1 6


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
A = np.random.randint(1, 6, size=(8, 3))
B = np.random.randint(1, 6, size=(2, 2))
for ar in A:
    aflag = 1
    for br in B:
        bflag = 0
        for el in br:
            if el in ar:
                bflag = 1
                break
        aflag *= bflag
    if aflag:
        print(ar)

[1 4 4]
[5 1 2]
[5 4 3]
[2 5 5]
[5 2 2]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [22]:
a = np.random.randint(1, 3, size=(10, 3))
for i in [j for j in range(len(a)) if len(set(a[j])) == 1]:
       a = np.delete(a, i, 0)
a

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 2],
       [2, 1, 2],
       [2, 1, 1],
       [2, 1, 2],
       [1, 1, 2],
       [2, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [23]:
array = np.random.randint(1, 4, size=(3, 3))
np.unique(array, axis=0)

array([[1, 3, 3],
       [3, 3, 1]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [24]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
product = np.prod(np.diag(X)[np.diag(X)!=0])
product

3

In [25]:
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
product = 1
for i in range(len(X)):
    for j in range(len(X[0])):
        if i == j and X[i][j] != 0:
            product *= X[i][j] 
product

3

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [26]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
array_1 = np.sort(x)
array_2 = np.sort(y)
if np.array_equal(array_1, array_2):
    print('True')
else:
    print('False')

True


In [27]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
x.sort()
y.sort()
if len(x) == len(y):
    for i in range(len(x)):
        if x[i] != y[i]:
            print('False')
            break
    print('True')
else:
    print('False')

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [28]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max_numbers_list = []
for i in range(1, len(x)):
    if x[i-1] == 0:
        max_numbers_list.append(x[i])
max_number = max(max_numbers_list)
max_number

5

In [29]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.max(np.where(x[:-1] == 0))

5

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [30]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
numbers, counter = np.unique(x, return_counts=True)
numbers, counter

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))

In [31]:
x = [2, 2, 2, 3, 3, 3, 5]
my_set = set(x)
counter_list = []
for i in my_set:
    counter_list.append(x.count(i))
counter = np.array(counter_list)
numbers = np.array(list(my_set))
numbers, counter

(array([2, 3, 5]), array([3, 3, 1]))

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [32]:
#distance for two points with coordinates
X = np.array((1, 2, 3))
Y = np.array((4, 5, 7))
dist = np.sqrt(np.sum(np.square(X - Y)))
dist

5.830951894845301

In [33]:
#distance for two points with coordinates
import math
X = [1, 2, 3]
Y = [4, 5, 7]
dist = math.dist(X, Y)
dist

5.830951894845301

In [34]:
#distance for two matrixes (using distance for two points with coordinates)
import math
X = [[3, 5, 0],
       [2, 6, 2],
       [4, 4, 6],
       [3, 0, 6],
       [4, 7, 6]]
Y = [[7, 1, 5],
       [7, 9, 2],
       [4, 8, 1],
       [2, 1, 1]]
result_matr = []
for i in range(len(X)):
    row = []
    for j in range(len(Y)):
        row.append(math.dist(X[i], Y[j]))
    result_matr.append(row)
result_matr

[[7.54983443527075, 6.0, 3.3166247903554003, 4.242640687119285],
 [7.681145747868609, 5.8309518948453, 3.0, 5.099019513592785],
 [4.358898943540673,
  7.0710678118654755,
  6.4031242374328485,
  6.164414002968977],
 [4.242640687119285, 10.63014581273465, 9.486832980505138, 5.196152422706632],
 [6.782329983125267, 5.385164807134504, 5.099019513592785, 8.06225774829855]]

In [35]:
#distance for two matrixes
X = np.array([[3, 5, 0],
       [2, 6, 2],
       [4, 4, 6],
       [3, 0, 6],
       [4, 7, 6]])
Y = np.array([[7, 1, 5],
       [7, 9, 2],
       [4, 8, 1],
       [2, 1, 1]])
P = np.add.outer(np.sum(X**2, axis=1), np.sum(Y**2, axis=1))
N = np.dot(X, Y.T)
np.sqrt(P - 2*N)

array([[ 7.54983444,  6.        ,  3.31662479,  4.24264069],
       [ 7.68114575,  5.83095189,  3.        ,  5.09901951],
       [ 4.35889894,  7.07106781,  6.40312424,  6.164414  ],
       [ 4.24264069, 10.63014581,  9.48683298,  5.19615242],
       [ 6.78232998,  5.38516481,  5.09901951,  8.06225775]])

In [40]:
#let's measure the speed of the code above
import timeit

code_to_test = """import numpy as np
X = np.array([[3, 5, 0],
       [2, 6, 2],
       [4, 4, 6],
       [3, 0, 6],
       [4, 7, 6]])
Y = np.array([[7, 1, 5],
       [7, 9, 2],
       [4, 8, 1],
       [2, 1, 1]])
P = np.add.outer(np.sum(X**2, axis=1), np.sum(Y**2, axis=1))
N = np.dot(X, Y.T)
np.sqrt(P - 2*N)
"""

elapsed_time = timeit.timeit(code_to_test, number=1)
print(elapsed_time)

0.00029760000006717746


In [37]:
#let's measure the speed of scipy.spatial.distance.cdist
import timeit

code_to_test = """
import scipy
from scipy.spatial import distance
import numpy as np
X = np.array([[3, 5, 0],
       [2, 6, 2],
       [4, 4, 6],
       [3, 0, 6],
       [4, 7, 6]])
Y = np.array([[7, 1, 5],
       [7, 9, 2],
       [4, 8, 1],
       [2, 1, 1]])
scipy.spatial.distance.cdist(X, Y, metric='euclidean',out=None)"""

elapsed_time = timeit.timeit(code_to_test, number=1)
print(elapsed_time)

0.6455768999999236


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [41]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [42]:
calorie_stats = np.loadtxt("cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [43]:
average_calories = calorie_stats.mean() - 60
average_calories

46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [44]:
calorie_stats_sorted = sorted(calorie_stats)
calorie_stats_sorted

[50.0,
 50.0,
 50.0,
 70.0,
 70.0,
 80.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 130.0,
 130.0,
 140.0,
 140.0,
 140.0,
 150.0,
 150.0,
 160.0]

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [45]:
median_calories = np.median(calorie_stats)
avg_calories = calorie_stats.mean()
median_calories, avg_calories

(110.0, 106.88311688311688)

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [46]:
np.percentile(calorie_stats, 50)
np.percentile(calorie_stats, 25)
np.percentile(calorie_stats, 10)
np.percentile(calorie_stats, 5)
np.percentile(calorie_stats, 3)
np.percentile(calorie_stats, 3.3)
nth_percentile = np.percentile(calorie_stats, 3.3)
nth_percentile

60.16

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [47]:
more_calories =  (len(calorie_stats[(calorie_stats >60)])) / len(calorie_stats) * 100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [48]:
calorie_std = np.std(calorie_stats)
calorie_std
#стандартное отклонение показывает, насколько сильный идет разброс данных. Мы можем показать, что основная часть сконцентрирована вокруг среднего значения, значит у нас достаточно особенные хлопья :)

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
Процентиль и соотношение с количеством калорий своих конкурентов говорит само за себя:
только 3.3% производителей имеют хлопья, у которых калории ниже наших! 
CrunchieMunchies определенно в топе для тех, кто предпочитает низкокалорийную диету
В целом, медиана и среднее значение так же достаточно показательны: наши хлопья содержат примерно на 50% меньше калорий чем у среднего значения.
